namespace Plateaumed.EHR.Misc.Json.PhysicalExaminations
{
    public class CardiovascularExaminationJson
    {
        public static readonly string jsonData = /*lang=json*/ @"[
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Nail examination- NAD"",
        ""SnomedId"": ""274764000"",
        ""AbsentTerms"": ""Abnormality detected in nail"",
        ""AbsentTermsSnomedId"": ""274764000:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Cyanosis of nail bed"",
        ""SnomedId"": ""722372005"",
        ""AbsentTerms"": ""Cyanosis of nail bed absent"",
        ""AbsentTermsSnomedId"": ""722372005:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Cyanosis"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Pale nail bed"",
        ""SnomedId"": ""719193000"",
        ""AbsentTerms"": ""Pallor of nail bed absent"",
        ""AbsentTermsSnomedId"": ""719193000:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Finger clubbing present"",
        ""SnomedId"": ""30760008"",
        ""AbsentTerms"": ""No finger clubbing"",
        ""AbsentTermsSnomedId"": ""267030001"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Digital Clubbing"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Normal nail"",
        ""SnomedId"": ""297988008"",
        ""AbsentTerms"": ""Nail abnormality"",
        ""AbsentTermsSnomedId"": ""297988008:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Quinke's sign present"",
        ""SnomedId"": ""70124003"",
        ""AbsentTerms"": ""Quinke's sign absent"",
        ""AbsentTermsSnomedId"": ""70124003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Splinter hemorrhages under nail"",
        ""SnomedId"": ""271770005"",
        ""AbsentTerms"": ""Splinter hemorrhages under nail absent"",
        ""AbsentTermsSnomedId"": ""271770005"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Hand - Arachnodactyly present"",
        ""SnomedId"": ""62250003"",
        ""AbsentTerms"": ""Hand - Arachnodactyly absent"",
        ""AbsentTermsSnomedId"": ""62250003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Hand - Xanthomata present"",
        ""SnomedId"": ""63103006"",
        ""AbsentTerms"": ""Hand - Xanthomata absent"",
        ""AbsentTermsSnomedId"": ""63103006:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Hand - Janeway lesions present"",
        ""SnomedId"": ""414550002"",
        ""AbsentTerms"": ""Hand - Janeway lesions absent"",
        ""AbsentTermsSnomedId"": ""414550002:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Osler's node of hand present"",
        ""SnomedId"": ""248520009"",
        ""AbsentTerms"": ""Osler's node of hand absent"",
        ""AbsentTermsSnomedId"": ""248520009:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Foot - Arachnodactyly present"",
        ""SnomedId"": ""62250003"",
        ""AbsentTerms"": ""Foot - Arachnodactyly absent"",
        ""AbsentTermsSnomedId"": ""62250003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Foot - Xanthoma present"",
        ""SnomedId"": ""63103006"",
        ""AbsentTerms"": ""Foot - Xanthoma absent"",
        ""AbsentTermsSnomedId"": ""63103006:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Foot - Janeway lesions present"",
        ""SnomedId"": ""414550002"",
        ""AbsentTerms"": ""Foot - Janeway lesions absent"",
        ""AbsentTermsSnomedId"": ""414550002:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Oslers node foot present"",
        ""SnomedId"": ""302176003"",
        ""AbsentTerms"": ""Oslers node foot absent"",
        ""AbsentTermsSnomedId"": ""302176003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Warm extremities"",
        ""SnomedId"": ""424818000"",
        ""AbsentTerms"": ""Cold extremities"",
        ""AbsentTermsSnomedId"": ""771542000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Skin Temperature"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""No pedal edema"",
        ""SnomedId"": ""102576009:272519000=2667000"",
        ""AbsentTerms"": ""Pedal edema observed"",
        ""AbsentTermsSnomedId"": ""102576009"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Oedema"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Normal capillary refill time"",
        ""SnomedId"": ""45332005"",
        ""AbsentTerms"": ""Capillary refill time not within reference range"",
        ""AbsentTermsSnomedId"": ""45332005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Increased capillary refill time"",
        ""SnomedId"": ""50427001"",
        ""AbsentTerms"": ""Capillary refill time not increased"",
        ""AbsentTermsSnomedId"": ""50427001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Hands and feet"",
        ""PresentTerms"": ""Decreased capillary refill time"",
        ""SnomedId"": ""27157002"",
        ""AbsentTerms"": ""Capillary refill time not decreased"",
        ""AbsentTermsSnomedId"": ""27157002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Pulse present"",
        ""SnomedId"": ""8499008:373573001=52101004"",
        ""AbsentTerms"": ""Pulse absent"",
        ""AbsentTermsSnomedId"": ""54518005"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Pulse impalpable"",
        ""SnomedId"": ""297210000"",
        ""AbsentTerms"": ""Pulse palpable"",
        ""AbsentTermsSnomedId"": ""301146007"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Pulse rate within reference range"",
        ""SnomedId"": ""10675001"",
        ""AbsentTerms"": ""Pulse rate outside reference range"",
        ""AbsentTermsSnomedId"": ""111972009"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Pulse rate outside reference range"",
        ""SnomedId"": ""111972009"",
        ""AbsentTerms"": ""Pulse rate within reference range"",
        ""AbsentTermsSnomedId"": ""10675001"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Pulse Rate"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Pulse irregular"",
        ""SnomedId"": ""61086009"",
        ""AbsentTerms"": ""Pulse regular"",
        ""AbsentTermsSnomedId"": ""271636001"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Pulse Rhythm"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Pulse regular"",
        ""SnomedId"": ""271636001"",
        ""AbsentTerms"": ""Pulse irregular"",
        ""AbsentTermsSnomedId"": ""61086009"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Delayed pulse present"",
        ""SnomedId"": ""248636001"",
        ""AbsentTerms"": ""Delayed pulse absent"",
        ""AbsentTermsSnomedId"": ""248636001:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Delayed pulse"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Plateau pulse"",
        ""SnomedId"": ""271641009"",
        ""AbsentTerms"": ""Plateau pulse absent"",
        ""AbsentTermsSnomedId"": ""271641009:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Rapid upstroke pulse"",
        ""SnomedId"": ""248635002"",
        ""AbsentTerms"": ""Rapid upstroke pulse absent"",
        ""AbsentTermsSnomedId"": ""248635002:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Unequal pulse"",
        ""SnomedId"": ""248633009"",
        ""AbsentTerms"": ""Unequal pulse absent"",
        ""AbsentTermsSnomedId"": ""248633009:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Slow rising pulse"",
        ""SnomedId"": ""248634003"",
        ""AbsentTerms"": ""Slow rising pulse absent"",
        ""AbsentTermsSnomedId"": ""248634003:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Collapsing pulse"",
        ""SnomedId"": ""44922000"",
        ""AbsentTerms"": ""Collapsing pulse absent"",
        ""AbsentTermsSnomedId"": ""44922000:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Pulse volume palpated"",
        ""SnomedId"": ""248642002:373573001=52101004"",
        ""AbsentTerms"": ""Pulse volume not palpated"",
        ""AbsentTermsSnomedId"": ""248642002:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Pulse volume"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Pulse"",
        ""PresentTerms"": ""Thickened arterial wall"",
        ""SnomedId"": ""271642002"",
        ""AbsentTerms"": ""Thickening of the arterial wall absent"",
        ""AbsentTermsSnomedId"": ""271642002:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Blood pressure within reference range while erect"",
        ""SnomedId"": ""2004005"",
        ""AbsentTerms"": ""Blood pressure outside reference range while erect"",
        ""AbsentTermsSnomedId"": ""38936003"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Blood pressure outside reference range while erect"",
        ""SnomedId"": ""38936003"",
        ""AbsentTerms"": ""Blood pressure within reference range while erect"",
        ""AbsentTermsSnomedId"": ""2004005"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Blood Pressure"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Blood pressure within reference range while supine"",
        ""SnomedId"": ""2004005"",
        ""AbsentTerms"": ""Blood pressure outside reference range while supine"",
        ""AbsentTermsSnomedId"": ""38936003"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Blood pressure outside reference range while supine"",
        ""SnomedId"": ""38936003"",
        ""AbsentTerms"": ""Blood pressure within reference range while supine"",
        ""AbsentTermsSnomedId"": ""2004005"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Blood Pressure"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Pulse pressure outside reference range"",
        ""SnomedId"": ""73654006"",
        ""AbsentTerms"": ""Pulse pressure outside reference range"",
        ""AbsentTermsSnomedId"": ""68603007"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Pulse Pressure"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Unequal blood pressure"",
        ""SnomedId"": ""102584008"",
        ""AbsentTerms"": ""No major blood pressure differences"",
        ""AbsentTermsSnomedId"": ""102584008:272519000=2667000"",
        ""Site"": true,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Korotkoff sound heard"",
        ""SnomedId"": ""85549003"",
        ""AbsentTerms"": ""Korotkoff sound absent"",
        ""AbsentTermsSnomedId"": ""85549003:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Blood pressure unrecordable"",
        ""SnomedId"": ""271645000"",
        ""AbsentTerms"": ""Blood pressure recordable"",
        ""AbsentTermsSnomedId"": ""2004005"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Postural drop in blood pressure"",
        ""SnomedId"": ""271648003"",
        ""AbsentTerms"": ""No postural drop in blood pressure"",
        ""AbsentTermsSnomedId"": ""271648003:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Labile blood pressure"",
        ""SnomedId"": ""251080003"",
        ""AbsentTerms"": ""Blood pressure not labile"",
        ""AbsentTermsSnomedId"": ""251080003:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Jugular venous distension"",
        ""SnomedId"": ""271653008"",
        ""AbsentTerms"": ""Jugular venous distension absent"",
        ""AbsentTermsSnomedId"": ""271653008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""JVP within reference range"",
        ""SnomedId"": ""369001"",
        ""AbsentTerms"": ""JVP outside reference range"",
        ""AbsentTermsSnomedId"": ""62436006"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""JVP outside reference range"",
        ""SnomedId"": ""62436006"",
        ""AbsentTerms"": ""JVP within reference range"",
        ""AbsentTermsSnomedId"": ""369001"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""JVP"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""BP and JVP"",
        ""PresentTerms"": ""Hepatojugular reflux- positive"",
        ""SnomedId"": ""72196001:260411009=10828004"",
        ""AbsentTerms"": ""Hepatojugular reflux- negative"",
        ""AbsentTermsSnomedId"": ""72196001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Conjuctival pallor present"",
        ""SnomedId"": ""719640000"",
        ""AbsentTerms"": ""Conjuctival pallor absent"",
        ""AbsentTermsSnomedId"": ""719640000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Corneal arcus present"",
        ""SnomedId"": ""231924000"",
        ""AbsentTerms"": ""Corneal arcus absent"",
        ""AbsentTermsSnomedId"": ""231924000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Xanthelasma present"",
        ""SnomedId"": ""238951005"",
        ""AbsentTerms"": ""Xanthelasma absent"",
        ""AbsentTermsSnomedId"": ""238951005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Kayser-Fleischer ring present"",
        ""SnomedId"": ""77103006"",
        ""AbsentTerms"": ""Kayser-Fleischer ring absent"",
        ""AbsentTermsSnomedId"": ""77103006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Central cyanosis"",
        ""SnomedId"": ""95837007"",
        ""AbsentTerms"": ""Central cyanosis absent"",
        ""AbsentTermsSnomedId"": ""95837007:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Angular stomatitis present"",
        ""SnomedId"": ""266429005"",
        ""AbsentTerms"": ""Angular stomatitis absent"",
        ""AbsentTermsSnomedId"": ""266429005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Good oral hygeine"",
        ""SnomedId"": ""278543008"",
        ""AbsentTerms"": ""Poor oral hygeine"",
        ""AbsentTermsSnomedId"": ""110299009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Facial oedema"",
        ""SnomedId"": ""445088006"",
        ""AbsentTerms"": ""No oedema of the face"",
        ""AbsentTermsSnomedId"": ""445088006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Flushed complexion"",
        ""SnomedId"": ""248213001"",
        ""AbsentTerms"": ""Complexion not flushed"",
        ""AbsentTermsSnomedId"": ""248213001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Face"",
        ""PresentTerms"": ""Sweating"",
        ""SnomedId"": ""415691001"",
        ""AbsentTerms"": ""Not visibly sweating"",
        ""AbsentTermsSnomedId"": ""415691001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Apex beat palpable"",
        ""SnomedId"": ""177029008"",
        ""AbsentTerms"": ""Apex beat impalpable"",
        ""AbsentTermsSnomedId"": ""399333009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Apex beat in normal location"",
        ""SnomedId"": ""301137001"",
        ""AbsentTerms"": ""Apex beat displaced"",
        ""AbsentTermsSnomedId"": ""248661003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Apex beat displaced"",
        ""SnomedId"": ""248661003"",
        ""AbsentTerms"": ""Apex beat not displaced"",
        ""AbsentTermsSnomedId"": ""248661003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Normal apex beat"",
        ""SnomedId"": ""301137001"",
        ""AbsentTerms"": ""Apex beat not normal"",
        ""AbsentTermsSnomedId"": ""301137001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Feeble apex beat"",
        ""SnomedId"": ""301136005"",
        ""AbsentTerms"": ""Apex beat not feeble"",
        ""AbsentTermsSnomedId"": ""301136005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Thrusting apex beat"",
        ""SnomedId"": ""301135009"",
        ""AbsentTerms"": ""Apex beat not thrusting"",
        ""AbsentTermsSnomedId"": ""301135009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Visible/ Prominent apex beat"",
        ""SnomedId"": ""248659007"",
        ""AbsentTerms"": ""Apex beat not prominent"",
        ""AbsentTermsSnomedId"": ""248659007:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Precordial heave present"",
        ""SnomedId"": ""421433001"",
        ""AbsentTerms"": ""Precordial heave absent"",
        ""AbsentTermsSnomedId"": ""421433001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Precordium"",
        ""PresentTerms"": ""Cardiac thrills present"",
        ""SnomedId"": ""271656000"",
        ""AbsentTerms"": ""Cardiac thrills absent"",
        ""AbsentTermsSnomedId"": ""274808009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Cardiac Thrill"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Heart"",
        ""PresentTerms"": ""First heart sound, S1 normal"",
        ""SnomedId"": ""47309005"",
        ""AbsentTerms"": ""S1 inaudible"",
        ""AbsentTermsSnomedId"": ""47309005:366185007=248668009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Heart sounds"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Heart"",
        ""PresentTerms"": ""Second heart sound, S2"",
        ""SnomedId"": ""28827006"",
        ""AbsentTerms"": ""S2 inaudible"",
        ""AbsentTermsSnomedId"": ""28827006:366185007=248668009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Heart sounds"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Heart"",
        ""PresentTerms"": ""Third heart sound, S3"",
        ""SnomedId"": ""277455002"",
        ""AbsentTerms"": ""S3 inaudible"",
        ""AbsentTermsSnomedId"": ""277455002:366185007=248668009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Heart sounds"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Heart"",
        ""PresentTerms"": ""Fourth heart sound, S4"",
        ""SnomedId"": ""48038003"",
        ""AbsentTerms"": ""S4 inaudible"",
        ""AbsentTermsSnomedId"": ""48038003:366185007=248668009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Heart sounds"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Heart"",
        ""PresentTerms"": ""Added heart sounds present"",
        ""SnomedId"": ""248690009"",
        ""AbsentTerms"": ""Added heart sounds absent"",
        ""AbsentTermsSnomedId"": ""248690009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Added sounds"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Heart"",
        ""PresentTerms"": ""Murmur present"",
        ""SnomedId"": ""414786004"",
        ""AbsentTerms"": ""Murmur absent"",
        ""AbsentTermsSnomedId"": ""301131000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Murmur"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Heart"",
        ""PresentTerms"": ""Venous hum"",
        ""SnomedId"": ""90658001"",
        ""AbsentTerms"": ""Venous hum absent"",
        ""AbsentTermsSnomedId"": ""90658001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Heart"",
        ""PresentTerms"": ""Pericardial friction rub"",
        ""SnomedId"": ""7036007"",
        ""AbsentTerms"": ""Pericardial friction rub absent"",
        ""AbsentTermsSnomedId"": ""301125003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Crepitations/Crackles present"",
        ""SnomedId"": ""284520004"",
        ""AbsentTerms"": ""Crepitations/Crackles absent"",
        ""AbsentTermsSnomedId"": ""284520004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Obvious chest deformity"",
        ""SnomedId"": ""448488004"",
        ""AbsentTerms"": ""Chest NAD"",
        ""AbsentTermsSnomedId"": ""830011000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Ventilation effortless, normal"",
        ""SnomedId"": ""80249004"",
        ""AbsentTerms"": ""Labored breathing"",
        ""AbsentTermsSnomedId"": ""248549001"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Vesicular breathing"",
        ""SnomedId"": ""77047003"",
        ""AbsentTerms"": ""Vesicular breathing absent"",
        ""AbsentTermsSnomedId"": ""77047003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Gurgles/rhonchi observed on auscultation"",
        ""SnomedId"": ""24612001"",
        ""AbsentTerms"": ""Gurgles/rhonchi observed on auscultation absent"",
        ""AbsentTermsSnomedId"": ""24612001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Flaring of alae nasi"",
        ""SnomedId"": ""21558008"",
        ""AbsentTerms"": ""Flaring of alae nasi absent"",
        ""AbsentTermsSnomedId"": ""21558008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Pursed lips on expiration"",
        ""SnomedId"": ""248564001"",
        ""AbsentTerms"": ""Pursed lips on expiration absent"",
        ""AbsentTermsSnomedId"": ""248564001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Dyspneic"",
        ""SnomedId"": ""162890008"",
        ""AbsentTerms"": ""Not breathless"",
        ""AbsentTermsSnomedId"": ""161938003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Wheezing"",
        ""SnomedId"": ""24612001"",
        ""AbsentTerms"": ""Wheezing absent"",
        ""AbsentTermsSnomedId"": ""310436000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Lungs"",
        ""PresentTerms"": ""Coughing"",
        ""SnomedId"": ""49727002"",
        ""AbsentTerms"": ""Coughing absent"",
        ""AbsentTermsSnomedId"": ""161922009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Abdominal distension"",
        ""SnomedId"": ""60728008"",
        ""AbsentTerms"": ""No abdominal distension"",
        ""AbsentTermsSnomedId"": ""162069004"",
        ""Site"": true,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Obese abdomen"",
        ""SnomedId"": ""249533007"",
        ""AbsentTerms"": ""Abdomen is not obese"",
        ""AbsentTermsSnomedId"": ""249533007:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Abdominal tenderness elicited"",
        ""SnomedId"": ""43478001"",
        ""AbsentTerms"": ""Abdominal tenderness absent"",
        ""AbsentTermsSnomedId"": ""297125009"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Abdominal mass"",
        ""SnomedId"": ""271860004"",
        ""AbsentTerms"": ""No abdominal mass"",
        ""AbsentTermsSnomedId"": ""860713000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Mass"",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Caput medusae present"",
        ""SnomedId"": ""402844009"",
        ""AbsentTerms"": ""Caput medusae absent"",
        ""AbsentTermsSnomedId"": ""402844009:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Striae present"",
        ""SnomedId"": ""201066002"",
        ""AbsentTerms"": ""Striae absent"",
        ""AbsentTermsSnomedId"": ""201066002:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Abdominal guarding present"",
        ""SnomedId"": ""249545003"",
        ""AbsentTerms"": ""Guarding absent"",
        ""AbsentTermsSnomedId"": ""249545003:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Shifting dullness identified"",
        ""SnomedId"": ""300425004"",
        ""AbsentTerms"": ""Shifting dullness absent"",
        ""AbsentTermsSnomedId"": ""300426003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Liver palpably enlarged"",
        ""SnomedId"": ""80515008"",
        ""AbsentTerms"": ""Liver is not palpably enlarged"",
        ""AbsentTermsSnomedId"": ""271679004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Tender hepatomegaly present"",
        ""SnomedId"": ""102627005"",
        ""AbsentTerms"": ""Tender hepatomegaly absent"",
        ""AbsentTermsSnomedId"": ""102627005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Aortic bruit perceived"",
        ""SnomedId"": ""248714006"",
        ""AbsentTerms"": ""Aortic bruit absent"",
        ""AbsentTermsSnomedId"": ""700424009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Renal bruit perceived"",
        ""SnomedId"": ""274728001"",
        ""AbsentTerms"": ""Renal bruit absent"",
        ""AbsentTermsSnomedId"": ""700426006"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    },
    {
        ""Header"": ""Liver"",
        ""PresentTerms"": ""Previous surgical scar visible"",
        ""SnomedId"": ""16646002"",
        ""AbsentTerms"": ""Scars absent"",
        ""AbsentTermsSnomedId"": ""16646002:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Cardiovascular""
    }
]";
    }
}