namespace Plateaumed.EHR.Misc.Json.PhysicalExaminations
{
    public class NeurologyExaminationJson
    {
        public static readonly string jsonData = /*lang=json*/ @"[
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Normal gait"",
        ""SnomedId"": ""8117002"",
        ""AbsentTerms"": ""Abnormal gait"",
        ""AbsentTermsSnomedId"": ""22325002"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Ataxic gait"",
        ""SnomedId"": ""25136009"",
        ""AbsentTerms"": ""Ataxic gait absent"",
        ""AbsentTermsSnomedId"": ""25136009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Shuffling gait"",
        ""SnomedId"": ""43005009"",
        ""AbsentTerms"": ""Shuffling gait absent"",
        ""AbsentTermsSnomedId"": ""43005009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Steppage gait"",
        ""SnomedId"": ""27253007"",
        ""AbsentTerms"": ""Steppage gait absent"",
        ""AbsentTermsSnomedId"": ""27253007"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Spastic gait"",
        ""SnomedId"": ""9447003"",
        ""AbsentTerms"": ""Spastic gait absent"",
        ""AbsentTermsSnomedId"": ""9447003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Scissors gait"",
        ""SnomedId"": ""102992006"",
        ""AbsentTerms"": ""Scissors gait absent"",
        ""AbsentTermsSnomedId"": ""102992006"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Antalgic gait"",
        ""SnomedId"": ""67141003"",
        ""AbsentTerms"": ""Antalgic gait absent"",
        ""AbsentTermsSnomedId"": ""67141003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Stumbling gait"",
        ""SnomedId"": ""250991000119100"",
        ""AbsentTerms"": ""Stumbling gait absent"",
        ""AbsentTermsSnomedId"": ""250991000119100"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Gait stable"",
        ""SnomedId"": ""449811004"",
        ""AbsentTerms"": ""Gait unstable"",
        ""AbsentTermsSnomedId"": ""22631008"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Gait"",
        ""PresentTerms"": ""Walking aid present"",
        ""SnomedId"": ""105504002"",
        ""AbsentTerms"": ""Walking aid absent"",
        ""AbsentTermsSnomedId"": ""165252001"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Walking aids suggestion"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Neck normal"",
        ""SnomedId"": ""840674001"",
        ""AbsentTerms"": ""Neck abnormality identified"",
        ""AbsentTermsSnomedId"": ""724620008"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Head/neck region tender"",
        ""SnomedId"": ""301401001"",
        ""AbsentTerms"": ""Head/neck region non-tender"",
        ""AbsentTermsSnomedId"": ""300821004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Mass/lump of neck visible"",
        ""SnomedId"": ""299703001"",
        ""AbsentTerms"": ""Neck lump/mass absent"",
        ""AbsentTermsSnomedId"": ""299703001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Mass"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Neck blister"",
        ""SnomedId"": ""271108005"",
        ""AbsentTerms"": ""Neck blister absent"",
        ""AbsentTermsSnomedId"": ""271108005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Extensiveness"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Neck stiffness"",
        ""SnomedId"": ""161882006"",
        ""AbsentTerms"": ""No stiff neck"",
        ""AbsentTermsSnomedId"": ""161881004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Nuchal rigidity"",
        ""SnomedId"": ""405947006"",
        ""AbsentTerms"": ""No nuchal rigidity"",
        ""AbsentTermsSnomedId"": ""405947006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Kernig's sign positive"",
        ""SnomedId"": ""124743003"",
        ""AbsentTerms"": ""Kernig's sign negative"",
        ""AbsentTermsSnomedId"": ""299730006"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Brudzinski's sign positive"",
        ""SnomedId"": ""124744009"",
        ""AbsentTerms"": ""Brudzinski's sign negative"",
        ""AbsentTermsSnomedId"": ""299731005"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Neck"",
        ""PresentTerms"": ""Visible surgical scar present"",
        ""SnomedId"": ""16646002"",
        ""AbsentTerms"": ""Scars absent"",
        ""AbsentTermsSnomedId"": ""16646002:272519000=2667000"",
        ""Site"": true,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Fully conscious"",
        ""SnomedId"": ""271591004"",
        ""AbsentTerms"": ""Unconscious"",
        ""AbsentTermsSnomedId"": ""418107008"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Awake"",
        ""SnomedId"": ""248218005"",
        ""AbsentTerms"": ""Not awake"",
        ""AbsentTermsSnomedId"": ""248220008"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Mentally alert"",
        ""SnomedId"": ""248234008"",
        ""AbsentTerms"": ""Lack of awareness"",
        ""AbsentTermsSnomedId"": ""406124004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Fluctuating level of consciousness"",
        ""SnomedId"": ""830285008"",
        ""AbsentTerms"": ""No fluctuating level of consciousness"",
        ""AbsentTermsSnomedId"": ""830285008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Clouded consciousness"",
        ""SnomedId"": ""40917007"",
        ""AbsentTerms"": ""Consciousness not clouded"",
        ""AbsentTermsSnomedId"": ""40917007:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Responsive"",
        ""SnomedId"": ""80074009"",
        ""AbsentTerms"": ""Unresponsive"",
        ""AbsentTermsSnomedId"": ""422768004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Lethargic"",
        ""SnomedId"": ""214264003"",
        ""AbsentTerms"": ""Not lethargic"",
        ""AbsentTermsSnomedId"": ""214264003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Drowsy"",
        ""SnomedId"": ""271782001"",
        ""AbsentTerms"": ""Not drowsy"",
        ""AbsentTermsSnomedId"": ""271782001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Conscious and alert"",
        ""SnomedId"": ""162701007"",
        ""AbsentTerms"": ""Unconscious/comatose"",
        ""AbsentTermsSnomedId"": ""268913004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Palinesthesia"",
        ""SnomedId"": ""83779006"",
        ""AbsentTerms"": ""Palinesthesia absent"",
        ""AbsentTermsSnomedId"": ""83779006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Amorphosynthesis"",
        ""SnomedId"": ""90406001"",
        ""AbsentTerms"": ""Amorphosynthesis absent"",
        ""AbsentTermsSnomedId"": ""90406001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Consciousness"",
        ""PresentTerms"": ""Postconcussion state"",
        ""SnomedId"": ""11764003"",
        ""AbsentTerms"": ""Not in postconcussion state"",
        ""AbsentTermsSnomedId"": ""11764003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Orientated"",
        ""SnomedId"": ""247663003"",
        ""AbsentTerms"": ""Disoriented"",
        ""AbsentTermsSnomedId"": ""62476001"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Good"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Oriented to person, time and place"",
        ""SnomedId"": ""426224004"",
        ""AbsentTerms"": ""Not orientated in time, place or person"",
        ""AbsentTermsSnomedId"": ""426224004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Orientated in time"",
        ""SnomedId"": ""426794005"",
        ""AbsentTerms"": ""Disorientated in time"",
        ""AbsentTermsSnomedId"": ""19657006"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Orientated in place"",
        ""SnomedId"": ""427161009"",
        ""AbsentTerms"": ""Disorientated in place"",
        ""AbsentTermsSnomedId"": ""72440003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Orientated in person"",
        ""SnomedId"": ""427645006"",
        ""AbsentTerms"": ""Disorientated in person"",
        ""AbsentTermsSnomedId"": ""62766000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Orientation good"",
        ""SnomedId"": ""247663003"",
        ""AbsentTerms"": ""Orientation poor"",
        ""AbsentTermsSnomedId"": ""62476001"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Decrease in level of disorientation   "",
        ""SnomedId"": ""1144864005"",
        ""AbsentTerms"": ""No decrease in level of disorientation   "",
        ""AbsentTermsSnomedId"": ""1144864005"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Disorientation as to self  "",
        ""SnomedId"": ""66797003"",
        ""AbsentTerms"": ""No disorientation as to self ."",
        ""AbsentTermsSnomedId"": ""66797003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Spatial disorientation"",
        ""SnomedId"": ""112077003"",
        ""AbsentTerms"": ""No spatial disorientation"",
        ""AbsentTermsSnomedId"": ""112077003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Orientation"",
        ""PresentTerms"": ""Right-left disorientation"",
        ""SnomedId"": ""1943009"",
        ""AbsentTerms"": ""No right-left disorientation"",
        ""AbsentTermsSnomedId"": ""1943009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: address recall successful"",
        ""SnomedId"": ""165307002"",
        ""AbsentTerms"": ""Memory: address recall unsuccessful"",
        ""AbsentTermsSnomedId"": ""165308007"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: count down successful"",
        ""SnomedId"": ""165304009"",
        ""AbsentTerms"": ""Memory: count down unsuccessful"",
        ""AbsentTermsSnomedId"": ""165305005"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: important event known"",
        ""SnomedId"": ""165299008"",
        ""AbsentTerms"": ""Memory: important event unknown"",
        ""AbsentTermsSnomedId"": ""165298000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: important person known"",
        ""SnomedId"": ""165302008"",
        ""AbsentTerms"": ""Memory: important person unknown"",
        ""AbsentTermsSnomedId"": ""165301001"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: own age known"",
        ""SnomedId"": ""165281000"",
        ""AbsentTerms"": ""Memory: own age not known"",
        ""AbsentTermsSnomedId"": ""165280004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: own DOB known"",
        ""SnomedId"": ""165293009"",
        ""AbsentTerms"": ""Memory: own DOB not known"",
        ""AbsentTermsSnomedId"": ""165293009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: present month known"",
        ""SnomedId"": ""165296001"",
        ""AbsentTerms"": ""Memory: present month unknown"",
        ""AbsentTermsSnomedId"": ""165295002"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: present place known"",
        ""SnomedId"": ""165287001"",
        ""AbsentTerms"": ""Memory: present place unknown"",
        ""AbsentTermsSnomedId"": ""165286005"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: present time known"",
        ""SnomedId"": ""165284008"",
        ""AbsentTerms"": ""Memory: present time unknown"",
        ""AbsentTermsSnomedId"": ""165283002"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Memory"",
        ""PresentTerms"": ""Memory: present year known"",
        ""SnomedId"": ""165290007"",
        ""AbsentTerms"": ""Memory: present year unknown"",
        ""AbsentTermsSnomedId"": ""165289003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Intellect"",
        ""SnomedId"": ""247572002"",
        ""AbsentTerms"": ""Limited intellect"",
        ""AbsentTermsSnomedId"": ""228156007"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Good"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Attention"",
        ""SnomedId"": ""6769007"",
        ""AbsentTerms"": ""Lack of attention"",
        ""AbsentTermsSnomedId"": ""22058002"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Normal reasoning"",
        ""SnomedId"": ""304642007"",
        ""AbsentTerms"": ""Unable to reason"",
        ""AbsentTermsSnomedId"": ""304643002"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Able to reason"",
        ""SnomedId"": ""304642007"",
        ""AbsentTerms"": ""Lack of thinking ability"",
        ""AbsentTermsSnomedId"": ""110355003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Difficulty reasoning"",
        ""SnomedId"": ""304644008"",
        ""AbsentTerms"": ""No difficulty reasoning"",
        ""AbsentTermsSnomedId"": ""304644008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Normal arithmetic reasoning"",
        ""SnomedId"": ""304660007"",
        ""AbsentTerms"": ""Lack of arithmetic reasoning"",
        ""AbsentTermsSnomedId"": ""304661006"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Difficulty using arithmetic reasoning"",
        ""SnomedId"": ""304662004"",
        ""AbsentTerms"": ""No difficulty using arithmetic reasoning"",
        ""AbsentTermsSnomedId"": ""304662004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Normal verbal reasoning"",
        ""SnomedId"": ""304664003"",
        ""AbsentTerms"": ""Lack of verbal reasoning"",
        ""AbsentTermsSnomedId"": ""304665002"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Difficulty using verbal reasoning"",
        ""SnomedId"": ""304666001"",
        ""AbsentTerms"": ""No difficulty using verbal reasoning"",
        ""AbsentTermsSnomedId"": ""304666001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Normal visuospatial reasoning"",
        ""SnomedId"": ""304655008"",
        ""AbsentTerms"": ""Lack of visuospatial reasoning"",
        ""AbsentTermsSnomedId"": ""304656009"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Difficulty using visuospatial reasoning"",
        ""SnomedId"": ""304657000"",
        ""AbsentTerms"": ""No difficulty using visuospatial reasoning"",
        ""AbsentTermsSnomedId"": ""304657000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Judgement"",
        ""SnomedId"": ""61254005"",
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": """",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Intelligence"",
        ""PresentTerms"": ""Judgement intact"",
        ""SnomedId"": ""709134004"",
        ""AbsentTerms"": ""Judgement lost"",
        ""AbsentTermsSnomedId"": ""162327005"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Speech"",
        ""SnomedId"": ""106132005"",
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": """",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Speech normal"",
        ""SnomedId"": ""162293002"",
        ""AbsentTerms"": ""Speech absent"",
        ""AbsentTermsSnomedId"": ""286369003"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Dysphasia"",
        ""SnomedId"": ""20301004"",
        ""AbsentTerms"": ""No dysphasia"",
        ""AbsentTermsSnomedId"": ""20301004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Fluency"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Aphasia"",
        ""SnomedId"": ""87486003"",
        ""AbsentTerms"": ""No aphasia"",
        ""AbsentTermsSnomedId"": ""87486003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Fluency"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Dysarthria"",
        ""SnomedId"": ""8011004"",
        ""AbsentTerms"": ""No dysarthria"",
        ""AbsentTermsSnomedId"": ""8011004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Fluency"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Anarthria"",
        ""SnomedId"": ""48257004"",
        ""AbsentTerms"": ""No anarthria"",
        ""AbsentTermsSnomedId"": ""48257004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Fluency"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Able to make speech sounds"",
        ""SnomedId"": ""286254001"",
        ""AbsentTerms"": ""Unable to make speech sounds"",
        ""AbsentTermsSnomedId"": ""286255000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Does make speech sounds"",
        ""SnomedId"": ""286256004"",
        ""AbsentTerms"": ""Does not make speech sounds"",
        ""AbsentTermsSnomedId"": ""286257008"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Able to produce voice"",
        ""SnomedId"": ""286326006"",
        ""AbsentTerms"": ""Unable to produce voice"",
        ""AbsentTermsSnomedId"": ""286327002"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Does produce voice"",
        ""SnomedId"": ""286328007"",
        ""AbsentTerms"": ""Loss of voice"",
        ""AbsentTermsSnomedId"": ""44564008"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Aprosodic speech"",
        ""SnomedId"": ""25623008"",
        ""AbsentTerms"": ""Speech not aprosodic"",
        ""AbsentTermsSnomedId"": ""25623008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Explosive speech"",
        ""SnomedId"": ""102935005"",
        ""AbsentTerms"": ""Speech not exclusive"",
        ""AbsentTermsSnomedId"": ""102935005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Scanning speech"",
        ""SnomedId"": ""77420001"",
        ""AbsentTerms"": ""Speech not scanning"",
        ""AbsentTermsSnomedId"": ""77420001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Coherent speech"",
        ""SnomedId"": ""449511000124107"",
        ""AbsentTerms"": ""Speech not coherent"",
        ""AbsentTermsSnomedId"": ""449511000124107:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Intelligible speech"",
        ""SnomedId"": ""719401001"",
        ""AbsentTerms"": ""Unintelligible articulation"",
        ""AbsentTermsSnomedId"": ""289194007"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Limited enunciation"",
        ""SnomedId"": ""424650008"",
        ""AbsentTerms"": ""No limitation of enunciation"",
        ""AbsentTermsSnomedId"": ""424650008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Rambling speech"",
        ""SnomedId"": ""162208002"",
        ""AbsentTerms"": ""Speech not rambling"",
        ""AbsentTermsSnomedId"": ""162208002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Speech appropriate for developmental age"",
        ""SnomedId"": ""717272001"",
        ""AbsentTerms"": ""Disturbance in speech"",
        ""AbsentTermsSnomedId"": ""29164008"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Coprolalia"",
        ""SnomedId"": ""13446000"",
        ""AbsentTerms"": ""Coprolalia absent"",
        ""AbsentTermsSnomedId"": ""13446000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Lalling"",
        ""SnomedId"": ""84484006"",
        ""AbsentTerms"": ""No lalling"",
        ""AbsentTermsSnomedId"": ""84484006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Lisping"",
        ""SnomedId"": ""69577009"",
        ""AbsentTerms"": ""No lisping"",
        ""AbsentTermsSnomedId"": ""69577009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": "" Speech"",
        ""PresentTerms"": ""Paraphrasia"",
        ""SnomedId"": ""15880005"",
        ""AbsentTerms"": ""No paraphrasia"",
        ""AbsentTermsSnomedId"": ""15880005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Handedness"",
        ""PresentTerms"": ""Ambidextrous"",
        ""SnomedId"": ""23088002"",
        ""AbsentTerms"": ""Not ambidextrous"",
        ""AbsentTermsSnomedId"": ""23088002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Handedness"",
        ""PresentTerms"": ""Left Handed"",
        ""SnomedId"": ""87683000"",
        ""AbsentTerms"": ""Not left handed"",
        ""AbsentTermsSnomedId"": ""87683000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Handedness"",
        ""PresentTerms"": ""Right Handed"",
        ""SnomedId"": ""46669005"",
        ""AbsentTerms"": ""Not right handed"",
        ""AbsentTermsSnomedId"": ""46669005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Handedness"",
        ""PresentTerms"": ""Unknown Handedness"",
        ""SnomedId"": ""709880000"",
        ""AbsentTerms"": ""Known handedness"",
        ""AbsentTermsSnomedId"": ""57427004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN I"",
        ""PresentTerms"": ""Sense of smell normal"",
        ""SnomedId"": ""299900007"",
        ""AbsentTerms"": ""Loss of smell"",
        ""AbsentTermsSnomedId"": ""44169009"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN I"",
        ""PresentTerms"": ""Impaired sense of smell"",
        ""SnomedId"": ""83156004"",
        ""AbsentTerms"": ""No impairment of smell"",
        ""AbsentTermsSnomedId"": ""83156004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN I"",
        ""PresentTerms"": ""Altered sense of smell"",
        ""SnomedId"": ""112105008"",
        ""AbsentTerms"": ""No alteration of smell"",
        ""AbsentTermsSnomedId"": ""112105008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN I"",
        ""PresentTerms"": ""CN I Palsy"",
        ""SnomedId"": ""44695005"",
        ""AbsentTerms"": ""CN I Palsy absent"",
        ""AbsentTermsSnomedId"": ""44695005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Pupil normal"",
        ""SnomedId"": ""301950001"",
        ""AbsentTerms"": ""Pupil abnormal"",
        ""AbsentTermsSnomedId"": ""274093008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Physiologic anisocoria"",
        ""SnomedId"": ""404693002"",
        ""AbsentTerms"": ""No physiologic anisocoria"",
        ""AbsentTermsSnomedId"": ""404693002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Dilated pupil"",
        ""SnomedId"": ""37125009"",
        ""AbsentTerms"": ""Undilated pupil"",
        ""AbsentTermsSnomedId"": ""442306006"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Pupil size and shape normal"",
        ""SnomedId"": ""247011006"",
        ""AbsentTerms"": ""Pupil abnormal"",
        ""AbsentTermsSnomedId"": ""274093008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Pupil abnormal"",
        ""SnomedId"": ""274093008"",
        ""AbsentTerms"": ""Pupil normal"",
        ""AbsentTermsSnomedId"": ""247011006"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Size"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Constricted pupil"",
        ""SnomedId"": ""301939004"",
        ""AbsentTerms"": ""Pupil not constricted"",
        ""AbsentTermsSnomedId"": ""37125009"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Pupils equal"",
        ""SnomedId"": ""301943000"",
        ""AbsentTerms"": ""Pupils unequal"",
        ""AbsentTermsSnomedId"": ""13045009"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Pupil deformed"",
        ""SnomedId"": ""79017007"",
        ""AbsentTerms"": ""Pupil not deformed"",
        ""AbsentTermsSnomedId"": ""301950001"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Keyhole pupil"",
        ""SnomedId"": ""247012004"",
        ""AbsentTerms"": ""No keyhole pupil"",
        ""AbsentTermsSnomedId"": ""247012004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Pupil round"",
        ""SnomedId"": ""421356009"",
        ""AbsentTerms"": ""Pupil not round"",
        ""AbsentTermsSnomedId"": ""421356009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Normal visual acuity"",
        ""SnomedId"": ""82132006"",
        ""AbsentTerms"": ""Poor visual acuity"",
        ""AbsentTermsSnomedId"": ""170728008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Able to see"",
        ""SnomedId"": ""705075002"",
        ""AbsentTerms"": ""Unable to see"",
        ""AbsentTermsSnomedId"": ""705075002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Able to see using assistive device"",
        ""SnomedId"": ""719749006"",
        ""AbsentTerms"": ""Unable to see using assistive device"",
        ""AbsentTermsSnomedId"": ""719749006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Able to see with pinhole"",
        ""SnomedId"": ""419475002"",
        ""AbsentTerms"": ""Unable to see with pinhole"",
        ""AbsentTermsSnomedId"": ""419475002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Distance vision"",
        ""SnomedId"": ""260269001"",
        ""AbsentTerms"": ""No distance vision"",
        ""AbsentTermsSnomedId"": ""260269001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Good"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Near vision"",
        ""SnomedId"": ""260247008"",
        ""AbsentTerms"": ""No near vision"",
        ""AbsentTermsSnomedId"": ""260247008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Good"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Fundoscopy normal"",
        ""SnomedId"": ""164734008"",
        ""AbsentTerms"": ""Fundoscopy not normal"",
        ""AbsentTermsSnomedId"": ""164735009"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Relative afferent pupil defect"",
        ""SnomedId"": ""247015002"",
        ""AbsentTerms"": ""No relative afferent pupil defect"",
        ""AbsentTermsSnomedId"": ""247015002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Pupil afferent light reaction normal"",
        ""SnomedId"": ""366025006"",
        ""AbsentTerms"": ""Pupil afferent light reaction abnormal"",
        ""AbsentTermsSnomedId"": ""366025006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Wernicke's hemianopic pupil"",
        ""SnomedId"": ""247021003"",
        ""AbsentTerms"": ""Wernicke's hemianopic pupil absent"",
        ""AbsentTermsSnomedId"": ""247021003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Reactive accommodation reflex"",
        ""SnomedId"": ""827088007"",
        ""AbsentTerms"": ""No reactive accommodation reflex"",
        ""AbsentTermsSnomedId"": ""860639008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Poor focus"",
        ""SnomedId"": ""26720002"",
        ""AbsentTerms"": ""Focus not poor"",
        ""AbsentTermsSnomedId"": ""26720002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Slow to focus"",
        ""SnomedId"": ""246722005"",
        ""AbsentTerms"": ""Focus not slow"",
        ""AbsentTermsSnomedId"": ""246722005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Normal color vision"",
        ""SnomedId"": ""827066007"",
        ""AbsentTerms"": ""Abnormal color vision"",
        ""AbsentTermsSnomedId"": ""23289000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Color vision statutory standard"",
        ""SnomedId"": ""246671008"",
        ""AbsentTerms"": ""Color vision below statutory standard"",
        ""AbsentTermsSnomedId"": ""246672001"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Reduced color discrimination"",
        ""SnomedId"": ""246673006"",
        ""AbsentTerms"": ""Color discrimination not reduced"",
        ""AbsentTermsSnomedId"": ""246673006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Normal peripheral vision"",
        ""SnomedId"": ""144008"",
        ""AbsentTerms"": ""Abnormal peripheral vision"",
        ""AbsentTermsSnomedId"": ""12772003"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Conjugated visual deviation"",
        ""SnomedId"": ""1332008"",
        ""AbsentTerms"": ""No conjugated visual deviation"",
        ""AbsentTermsSnomedId"": ""1332008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""Normal visual field"",
        ""SnomedId"": ""830129007"",
        ""AbsentTerms"": ""Visual field defect"",
        ""AbsentTermsSnomedId"": ""12184005"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN II"",
        ""PresentTerms"": ""CN II Palsy"",
        ""SnomedId"": ""44695005"",
        ""AbsentTerms"": ""CN II Palsy absent"",
        ""AbsentTermsSnomedId"": ""44695005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""CN III intact"",
        ""SnomedId"": ""823983004"",
        ""AbsentTerms"": ""CN III not intact"",
        ""AbsentTermsSnomedId"": ""823983004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""CN IV intact"",
        ""SnomedId"": ""823991008"",
        ""AbsentTerms"": ""CN IV not intact"",
        ""AbsentTermsSnomedId"": ""823991008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""CN VI intact"",
        ""SnomedId"": ""823992001"",
        ""AbsentTerms"": ""CN VI not intact"",
        ""AbsentTermsSnomedId"": ""823992001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Eyelid normal"",
        ""SnomedId"": ""25911000175109"",
        ""AbsentTerms"": ""Eyelid abnormal"",
        ""AbsentTermsSnomedId"": ""25911000175109:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Lid lag present"",
        ""SnomedId"": ""89893000"",
        ""AbsentTerms"": ""Lid lag absent"",
        ""AbsentTermsSnomedId"": ""89893000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Ptosis present"",
        ""SnomedId"": ""274825006"",
        ""AbsentTerms"": ""Ptosis absent"",
        ""AbsentTermsSnomedId"": ""274824005"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Lower eyelid retraction"",
        ""SnomedId"": ""302015009"",
        ""AbsentTerms"": ""Lower eyelid retraction absent"",
        ""AbsentTermsSnomedId"": ""302015009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Upper eyelid retraction"",
        ""SnomedId"": ""302014008"",
        ""AbsentTerms"": ""Upper eyelid retraction absent"",
        ""AbsentTermsSnomedId"": ""302014008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Brisk pupil movement"",
        ""SnomedId"": ""421352006"",
        ""AbsentTerms"": ""No brisk pupil movement"",
        ""AbsentTermsSnomedId"": ""421352006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Pupil vermiform movement"",
        ""SnomedId"": ""247023000"",
        ""AbsentTerms"": ""No vermiform pupil movement"",
        ""AbsentTermsSnomedId"": ""247023000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Sector pupil palsy"",
        ""SnomedId"": ""247024006"",
        ""AbsentTerms"": ""No sector pupil palsy"",
        ""AbsentTermsSnomedId"": ""247024006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Sluggish pupil movement"",
        ""SnomedId"": ""421141009"",
        ""AbsentTerms"": ""No sluggish pupil movement"",
        ""AbsentTermsSnomedId"": ""421141009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Normal ocular motility"",
        ""SnomedId"": ""103251002"",
        ""AbsentTerms"": ""Does not move"",
        ""AbsentTermsSnomedId"": ""302001007"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Limited range of motion"",
        ""SnomedId"": ""419326002"",
        ""AbsentTerms"": ""Normal ocular motility"",
        ""AbsentTermsSnomedId"": ""103251002"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Direction"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Downdrift of eyes"",
        ""SnomedId"": ""246702006"",
        ""AbsentTerms"": ""No downwards eye movement"",
        ""AbsentTermsSnomedId"": ""817006005"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Updrift of eyes"",
        ""SnomedId"": ""246701004"",
        ""AbsentTerms"": ""No updrift of eyes"",
        ""AbsentTermsSnomedId"": ""246701004:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Nystagmus present"",
        ""SnomedId"": ""307699005"",
        ""AbsentTerms"": ""Nystagmus absent"",
        ""AbsentTermsSnomedId"": ""274826007"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Limited downward eye movement"",
        ""SnomedId"": ""418078000"",
        ""AbsentTerms"": ""No limitation of downward eye movement"",
        ""AbsentTermsSnomedId"": ""418078000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Limited leftward eye movement"",
        ""SnomedId"": ""419825008"",
        ""AbsentTerms"": ""No limitation of leftward eye movement"",
        ""AbsentTermsSnomedId"": ""419825008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Limited rightward eye movement"",
        ""SnomedId"": ""419566002"",
        ""AbsentTerms"": ""No limitation of rightward eye movement"",
        ""AbsentTermsSnomedId"": ""419566002:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Limited upward eye movement"",
        ""SnomedId"": ""420150003"",
        ""AbsentTerms"": ""No limitation of upward eye movement"",
        ""AbsentTermsSnomedId"": ""420150003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Displacement of pupil light reflex"",
        ""SnomedId"": ""246725007"",
        ""AbsentTerms"": ""Absence of pupil light reflex displacement"",
        ""AbsentTermsSnomedId"": ""246725007:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Heterotropia"",
        ""SnomedId"": ""128602000"",
        ""AbsentTerms"": ""Heterotropia absent"",
        ""AbsentTermsSnomedId"": ""128602000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Esotropia"",
        ""SnomedId"": ""16596007"",
        ""AbsentTerms"": ""Esotropia absent"",
        ""AbsentTermsSnomedId"": ""16596007:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Exotropia"",
        ""SnomedId"": ""399054005"",
        ""AbsentTerms"": ""Exotropia absent"",
        ""AbsentTermsSnomedId"": ""399054005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Intermittent tropia"",
        ""SnomedId"": ""74025007"",
        ""AbsentTerms"": ""Intermittent tropia absent"",
        ""AbsentTermsSnomedId"": ""74025007:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN III, IV & VI"",
        ""PresentTerms"": ""Manifest vertical squint"",
        ""SnomedId"": ""111530003"",
        ""AbsentTerms"": ""Manifest vertical squint absent"",
        ""AbsentTermsSnomedId"": ""111530003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""CN V Intact"",
        ""SnomedId"": ""823986007"",
        ""AbsentTerms"": ""CN V not intact"",
        ""AbsentTermsSnomedId"": ""823986007:272519000=2667000"",
        ""Site"": true,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""Light touch sensation present"",
        ""SnomedId"": ""299911004"",
        ""AbsentTerms"": ""Light touch sensation absent"",
        ""AbsentTermsSnomedId"": ""299912006"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""Normal light touch sensation"",
        ""SnomedId"": ""299914007"",
        ""AbsentTerms"": ""Impaired light touch sensation"",
        ""AbsentTermsSnomedId"": ""299913001"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""Pin prick discrimination present"",
        ""SnomedId"": ""299926002"",
        ""AbsentTerms"": ""Absent pin prick discrimination"",
        ""AbsentTermsSnomedId"": ""299927006"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""Normal pin prick discrimination"",
        ""SnomedId"": ""299929009"",
        ""AbsentTerms"": ""Impaired pin prick discrimination"",
        ""AbsentTermsSnomedId"": ""299928001"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""Normal pin prick discrimination on foot"",
        ""SnomedId"": ""299929009"",
        ""AbsentTerms"": ""Pin prick sensation of foot abnormal"",
        ""AbsentTermsSnomedId"": ""398894000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""Muscle wasting"",
        ""SnomedId"": ""88092000"",
        ""AbsentTerms"": ""No muscle wasting"",
        ""AbsentTermsSnomedId"": ""88092000:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""CN V Palsy"",
        ""SnomedId"": ""44695005"",
        ""AbsentTerms"": ""CN V Palsy absent"",
        ""AbsentTermsSnomedId"": ""44695005:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""Jaw reflex normal"",
        ""SnomedId"": ""299807006"",
        ""AbsentTerms"": ""Jaw reflex absent"",
        ""AbsentTermsSnomedId"": ""274821002"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Reflex"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN V"",
        ""PresentTerms"": ""Corneal reflex normal"",
        ""SnomedId"": ""299810004"",
        ""AbsentTerms"": ""Corneal reflex absent"",
        ""AbsentTermsSnomedId"": ""78710008"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Reflex"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VII"",
        ""PresentTerms"": ""CN VII Intact"",
        ""SnomedId"": ""823982009"",
        ""AbsentTerms"": ""CN VII not intact"",
        ""AbsentTermsSnomedId"": ""449991000124107"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VII"",
        ""PresentTerms"": ""Facial palsy"",
        ""SnomedId"": ""280816001"",
        ""AbsentTerms"": ""Facial palsy absent"",
        ""AbsentTermsSnomedId"": ""280816001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VII"",
        ""PresentTerms"": ""Facial sytremmy"",
        ""SnomedId"": ""248172007"",
        ""AbsentTerms"": ""Facial asytremmy"",
        ""AbsentTermsSnomedId"": ""15253005"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VII"",
        ""PresentTerms"": ""Facial spasm"",
        ""SnomedId"": ""32402008"",
        ""AbsentTerms"": ""Facial spasm absent"",
        ""AbsentTermsSnomedId"": ""32402008:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VII"",
        ""PresentTerms"": ""Facial tic"",
        ""SnomedId"": ""230335009"",
        ""AbsentTerms"": ""Facial tic absent"",
        ""AbsentTermsSnomedId"": ""230335009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VII"",
        ""PresentTerms"": ""Taste normal"",
        ""SnomedId"": ""299901006"",
        ""AbsentTerms"": ""Taste sense altered"",
        ""AbsentTermsSnomedId"": ""271801002"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VII"",
        ""PresentTerms"": ""Hearing normal"",
        ""SnomedId"": ""162339002"",
        ""AbsentTerms"": ""Hyperacusis"",
        ""AbsentTermsSnomedId"": ""247713003"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VIII"",
        ""PresentTerms"": ""Rinne's test positive"",
        ""SnomedId"": ""370378005"",
        ""AbsentTerms"": ""Rinne's test negative"",
        ""AbsentTermsSnomedId"": ""370377000"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VIII"",
        ""PresentTerms"": ""Air conduction better than bone"",
        ""SnomedId"": ""54376001"",
        ""AbsentTerms"": ""No difference in air or bone conduction"",
        ""AbsentTermsSnomedId"": ""247309008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VIII"",
        ""PresentTerms"": ""Bone conduction better than air"",
        ""SnomedId"": ""2521009"",
        ""AbsentTerms"": ""No difference in air or bone conduction"",
        ""AbsentTermsSnomedId"": ""247309008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN VIII"",
        ""PresentTerms"": ""Vestibulo-ocular reflex present"",
        ""SnomedId"": ""299817001"",
        ""AbsentTerms"": ""Vestibulo-ocular reflex absent"",
        ""AbsentTermsSnomedId"": ""299818006"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN IX & X"",
        ""PresentTerms"": ""Deviation of uvula"",
        ""SnomedId"": ""249884003"",
        ""AbsentTerms"": ""No deviation of uvula"",
        ""AbsentTermsSnomedId"": ""249884003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN IX & X"",
        ""PresentTerms"": ""Effective cough"",
        ""SnomedId"": ""301236000"",
        ""AbsentTerms"": ""Bovine cough"",
        ""AbsentTermsSnomedId"": ""62427007"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN IX & X"",
        ""PresentTerms"": ""Hyperactive pharyngeal gag reflex"",
        ""SnomedId"": ""286461000119106"",
        ""AbsentTerms"": ""Hypoactive gag reflex"",
        ""AbsentTermsSnomedId"": ""5799008"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN IX & X"",
        ""PresentTerms"": ""Pharyngeal gag reflex positive"",
        ""SnomedId"": ""299816005"",
        ""AbsentTerms"": ""Pharyngeal gag reflex negative"",
        ""AbsentTermsSnomedId"": ""5258001"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN XI"",
        ""PresentTerms"": ""CN XI intact"",
        ""SnomedId"": ""823985006"",
        ""AbsentTerms"": ""CN XI not intact"",
        ""AbsentTermsSnomedId"": ""823985006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN XI"",
        ""PresentTerms"": ""Muscle wasting"",
        ""SnomedId"": ""88092000"",
        ""AbsentTerms"": ""No muscle wasting"",
        ""AbsentTermsSnomedId"": ""88092000:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN XI"",
        ""PresentTerms"": ""CN XI Palsy"",
        ""SnomedId"": ""44695005"",
        ""AbsentTerms"": ""CN XI Palsy absent"",
        ""AbsentTermsSnomedId"": ""44695005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN XII"",
        ""PresentTerms"": ""CN XII intact"",
        ""SnomedId"": ""823978007"",
        ""AbsentTerms"": ""CN XII not intact"",
        ""AbsentTermsSnomedId"": ""823978007:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN XII"",
        ""PresentTerms"": ""Tongue wasting"",
        ""SnomedId"": ""249382006"",
        ""AbsentTerms"": ""No tongue wasting"",
        ""AbsentTermsSnomedId"": ""249382006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN XII"",
        ""PresentTerms"": ""Tongue fasciculation"",
        ""SnomedId"": ""249878001"",
        ""AbsentTerms"": ""No tongue fasciculation"",
        ""AbsentTermsSnomedId"": ""249878001:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""CN XII"",
        ""PresentTerms"": ""CN XII Palsy"",
        ""SnomedId"": ""44695005"",
        ""AbsentTerms"": ""CN XII Palsy absent"",
        ""AbsentTermsSnomedId"": ""44695005:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle fasciculation"",
        ""SnomedId"": ""82470000"",
        ""AbsentTerms"": ""No muscle fasciculation"",
        ""AbsentTermsSnomedId"": ""82470000:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle wasting"",
        ""SnomedId"": ""88092000"",
        ""AbsentTerms"": ""No muscle wasting"",
        ""AbsentTermsSnomedId"": ""88092000:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Tremor"",
        ""SnomedId"": ""26079004"",
        ""AbsentTerms"": ""No tremors"",
        ""AbsentTermsSnomedId"": ""26079004:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Involuntary movement"",
        ""SnomedId"": ""267078001"",
        ""AbsentTerms"": ""No involuntary movements"",
        ""AbsentTermsSnomedId"": ""274541004"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Involuntary Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Pronator drift"",
        ""SnomedId"": ""428334004"",
        ""AbsentTerms"": ""Pronator drift absent"",
        ""AbsentTermsSnomedId"": ""428334004:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal muscle tone"",
        ""SnomedId"": ""827065006"",
        ""AbsentTerms"": ""Muscle atonic"",
        ""AbsentTermsSnomedId"": ""19532005"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Muscle tone"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Atonic"",
        ""SnomedId"": ""19532005"",
        ""AbsentTerms"": ""Not atonic"",
        ""AbsentTermsSnomedId"": ""827065006:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle spasm"",
        ""SnomedId"": ""45352006"",
        ""AbsentTerms"": ""No muscle spasm"",
        ""AbsentTermsSnomedId"": ""45352006:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle rigid"",
        ""SnomedId"": ""16046003"",
        ""AbsentTerms"": ""No muscle rigiditiy"",
        ""AbsentTermsSnomedId"": ""16046003:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Muscle Rigidity"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle hypotonia"",
        ""SnomedId"": ""398152000"",
        ""AbsentTerms"": ""No muscle hypotonia"",
        ""AbsentTermsSnomedId"": ""398152000:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle flaccid"",
        ""SnomedId"": ""186611004"",
        ""AbsentTerms"": ""No muscle flaccidity"",
        ""AbsentTermsSnomedId"": ""186611004:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle power unequal"",
        ""SnomedId"": ""249947004"",
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": """",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle weakness"",
        ""SnomedId"": ""26544005"",
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": """",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Muscle power present"",
        ""SnomedId"": ""271708004"",
        ""AbsentTerms"": ""Muscle power absence"",
        ""AbsentTermsSnomedId"": ""827007000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""MRC grade"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Coordination present"",
        ""SnomedId"": ""302288005"",
        ""AbsentTerms"": ""Coordination absent"",
        ""AbsentTermsSnomedId"": ""281016006"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Incoordination"",
        ""SnomedId"": ""281016006"",
        ""AbsentTerms"": ""No incoordination"",
        ""AbsentTermsSnomedId"": ""162258009"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Adiadochokinesia"",
        ""SnomedId"": ""61691009"",
        ""AbsentTerms"": ""No adiadochokinesia"",
        ""AbsentTermsSnomedId"": ""61691009:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Dysdiadochokinesis"",
        ""SnomedId"": ""23133003"",
        ""AbsentTerms"": ""No dysdiadochokinesis"",
        ""AbsentTermsSnomedId"": ""23133003:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Past pointing"",
        ""SnomedId"": ""49768006"",
        ""AbsentTerms"": ""No past pointing"",
        ""AbsentTermsSnomedId"": ""49768006:272519000=2667000"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Finger-finger test normal"",
        ""SnomedId"": ""298323006"",
        ""AbsentTerms"": ""Finger-finger test abnormal"",
        ""AbsentTermsSnomedId"": ""250064001"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Finger-nose test normal"",
        ""SnomedId"": ""298324000"",
        ""AbsentTerms"": ""Finger-nose test abnormal"",
        ""AbsentTermsSnomedId"": ""250063007"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Heel-shin test normal"",
        ""SnomedId"": ""298318006"",
        ""AbsentTerms"": ""Heel-shin test abnormal"",
        ""AbsentTermsSnomedId"": ""250066004"",
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal shoulder abduction"",
        ""SnomedId"": ""298796006:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal shoulder abduction"",
        ""AbsentTermsSnomedId"": ""298796006:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal shoulder adduction"",
        ""SnomedId"": ""298808007:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal shoulder adduction"",
        ""AbsentTermsSnomedId"": ""298808007:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal elbow flexion"",
        ""SnomedId"": ""366506004:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal elbow flexion"",
        ""AbsentTermsSnomedId"": ""366506004:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal elbow extension"",
        ""SnomedId"": ""366509006:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal elbow extension"",
        ""AbsentTermsSnomedId"": ""366509006:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal wrist flexion"",
        ""SnomedId"": ""298947005:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal wrist flexion"",
        ""AbsentTermsSnomedId"": ""298947005:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal wrist extension"",
        ""SnomedId"": ""298958001:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal wrist extension"",
        ""AbsentTermsSnomedId"": ""298958001:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal finger extension"",
        ""SnomedId"": ""366677004:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal finger extension"",
        ""AbsentTermsSnomedId"": ""366677004:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal finger abduction"",
        ""SnomedId"": ""366681004:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal finger abduction"",
        ""AbsentTermsSnomedId"": ""366681004:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal thumb abduction"",
        ""SnomedId"": ""366694002:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal thumb abduction"",
        ""AbsentTermsSnomedId"": ""366694002:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Range of Movement"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal hip flexion"",
        ""SnomedId"": ""366561006:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal hip flexion"",
        ""AbsentTermsSnomedId"": ""366561006:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal knee flexion"",
        ""SnomedId"": ""366587006:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal knee flexion"",
        ""AbsentTermsSnomedId"": ""366587006:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal knee extension"",
        ""SnomedId"": ""366590000:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal knee extension"",
        ""AbsentTermsSnomedId"": ""366590000:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal ankle dorsiflexion"",
        ""SnomedId"": ""366615000:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal ankle dorsiflexion"",
        ""AbsentTermsSnomedId"": ""366615000:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Normal ankle extension"",
        ""SnomedId"": ""366618003:274761008=298228000"",
        ""AbsentTerms"": ""Abnormal ankle extension"",
        ""AbsentTermsSnomedId"": ""366618003:276800000=263654008"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Biceps reflex normal"",
        ""SnomedId"": ""299832008"",
        ""AbsentTerms"": ""Biceps reflex absent"",
        ""AbsentTermsSnomedId"": ""274820001"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Reflex"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Supinator reflex normal"",
        ""SnomedId"": ""299838007"",
        ""AbsentTerms"": ""Radial reflex absent"",
        ""AbsentTermsSnomedId"": ""274605005"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Reflex"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Triceps reflex normal"",
        ""SnomedId"": ""299826003"",
        ""AbsentTerms"": ""Triceps reflex absent"",
        ""AbsentTermsSnomedId"": ""274819007"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Reflex"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Knee reflex normal"",
        ""SnomedId"": ""299873009"",
        ""AbsentTerms"": ""Knee reflex absent"",
        ""AbsentTermsSnomedId"": ""274817009"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Reflex"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Ankle reflex normal"",
        ""SnomedId"": ""299879008"",
        ""AbsentTerms"": ""Ankle reflex absent"",
        ""AbsentTermsSnomedId"": ""274818004"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Reflex"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Motor Exam"",
        ""PresentTerms"": ""Plantar reflex normal"",
        ""SnomedId"": ""700407003"",
        ""AbsentTerms"": ""Plantar reflex absent"",
        ""AbsentTermsSnomedId"": ""246592003"",
        ""Site"": false,
        ""Plane"": true,
        ""Qualifiers"": ""Reflex"",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Light touch sensation present"",
        ""SnomedId"": ""299911004"",
        ""AbsentTerms"": ""Light touch sensation absent"",
        ""AbsentTermsSnomedId"": ""299912006"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Normal light touch sensation"",
        ""SnomedId"": ""299914007"",
        ""AbsentTerms"": ""Impaired light touch sensation"",
        ""AbsentTermsSnomedId"": ""299913001"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Pin prick discrimination present"",
        ""SnomedId"": ""299926002"",
        ""AbsentTerms"": ""Absent pin prick discrimination"",
        ""AbsentTermsSnomedId"": ""299927006"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Normal pin prick discrimination"",
        ""SnomedId"": ""299929009"",
        ""AbsentTerms"": ""Impaired pin prick discrimination"",
        ""AbsentTermsSnomedId"": ""299928001"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Vibration sensation present"",
        ""SnomedId"": ""299933002"",
        ""AbsentTerms"": ""Absence of vibratory sense"",
        ""AbsentTermsSnomedId"": ""80474004"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Normal vibration sensation"",
        ""SnomedId"": ""299935009"",
        ""AbsentTerms"": ""Decreased vibratory sense"",
        ""AbsentTermsSnomedId"": ""130980003"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Decreased vibratory sense"",
        ""SnomedId"": ""130980003"",
        ""AbsentTerms"": ""No decrease of vibration sense"",
        ""AbsentTermsSnomedId"": ""130980003:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Impaired vibration sensation"",
        ""SnomedId"": ""299934008"",
        ""AbsentTerms"": ""No impairment of vibration sense"",
        ""AbsentTermsSnomedId"": ""299934008:272519000=2667000"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": """",
        ""Type"": ""Neurology""
    },
    {
        ""Header"": ""Sensory Exam"",
        ""PresentTerms"": ""Proprioception normal"",
        ""SnomedId"": ""299936005:274761008=298228000"",
        ""AbsentTerms"": ""Proprioception abnormal"",
        ""AbsentTermsSnomedId"": ""299936005:276800000=263654008"",
        ""Site"": true,
        ""Plane"": true,
        ""Qualifiers"": ""Impairment"",
        ""Type"": ""Neurology""
    }
]";
    }
}