namespace Plateaumed.EHR.Misc.Json.PhysicalExaminations
{
    public class ObstetricsExaminationJson
    {
        public static readonly string jsonData = /*lang=json*/ @"[
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Ovoid pregnant abdomen"",
        ""SnomedId"": 289686004,
        ""AbsentTerms"": ""Abnormal uterine shape"",
        ""AbsentTermsSnomedId"": 92957000,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Rounded pregnant abdomen"",
        ""SnomedId"": 289687008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Transversely enlarged pregnant abdomen"",
        ""SnomedId"": 289688003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Calkin's sign"",
        ""SnomedId"": 70651004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Fetal movements visible"",
        ""SnomedId"": 169731002,
        ""AbsentTerms"": ""Fetal movements not observed"",
        ""AbsentTermsSnomedId"": 289433006,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Surgical scars"",
        ""SnomedId"": 442523003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Surgical Scar"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Linea nigra"",
        ""SnomedId"": 90751002,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Striae gravidarum"",
        ""SnomedId"": 271674009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Striae albicans"",
        ""SnomedId"": null,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Flat umbilicus"",
        ""SnomedId"": 271672008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Protuding umbilicus"",
        ""SnomedId"": 271672008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Sunken Umbilicus"",
        ""SnomedId"": 249540008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Visible abdominal mass"",
        ""SnomedId"": 300404004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Inspection"",
        ""PresentTerms"": ""Bandl’s ring"",
        ""SnomedId"": 79414005,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Fundal height measurement"",
        ""SnomedId"": 249016007,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Fundal Height"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Size of uterus"",
        ""SnomedId"": 248944004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Unit"": ""cm"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Abdominal tenderness present"",
        ""SnomedId"": 43478001,
        ""AbsentTerms"": ""Abdominal tenderness absent"",
        ""AbsentTermsSnomedId"": 297125009,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Abdominal mass present"",
        ""SnomedId"": 271860004,
        ""AbsentTerms"": ""No abdominal mass"",
        ""AbsentTermsSnomedId"": 860713000,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Fetal movements felt"",
        ""SnomedId"": 268470003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Size of uterus"",
        ""SnomedId"": 248944004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Number of fetus"",
        ""SnomedId"": 246435002,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Multiple fetal parts palpable"",
        ""SnomedId"": 249059002,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Fetal Lie"",
        ""SnomedId"": null,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Longitudinal lie"",
        ""SnomedId"": 249063009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Oblique lie"",
        ""SnomedId"": 63750008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Transverse lie"",
        ""SnomedId"": 73161006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Palpable fetal parts"",
        ""SnomedId"": 249059002,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Fetal Presentation"",
        ""SnomedId"": null,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Cephalic presentation"",
        ""SnomedId"": 1209182005,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Breech presentation"",
        ""SnomedId"": 6096002,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Brow presentation"",
        ""SnomedId"": 8014007,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Compound presentation"",
        ""SnomedId"": 124736009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Face presentation"",
        ""SnomedId"": 21882006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Funic presentation"",
        ""SnomedId"": 46200004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Fetal position"",
        ""SnomedId"": null,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Asynclitism"",
        ""SnomedId"": 14058000,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Occipitoanterior position"",
        ""SnomedId"": 90381008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Occipitolateral position"",
        ""SnomedId"": 249071008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal Palpation"",
        ""PresentTerms"": ""Occipitoposterior position"",
        ""SnomedId"": 37235006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal percussion"",
        ""PresentTerms"": ""Liver enlarged"",
        ""SnomedId"": 80515008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": true,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal percussion"",
        ""PresentTerms"": ""Liver tender"",
        ""SnomedId"": 102627005,
        ""AbsentTerms"": ""Liver non-tender"",
        ""AbsentTermsSnomedId"": 300334008,
        ""Site"": true,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Abdominal percussion"",
        ""PresentTerms"": ""Spleen enlarged"",
        ""SnomedId"": 249572006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Auscultation"",
        ""PresentTerms"": ""Fetal heart rate"",
        ""SnomedId"": 249043002,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Auscultation"",
        ""PresentTerms"": ""Relation with maternal pulse"",
        ""SnomedId"": null,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Synchronous or Asynchronus"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Fetus"",
        ""PresentTerms"": ""Fetal engagement"",
        ""SnomedId"": 364610007,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Unit"": ""Number of Fingers"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Fetus"",
        ""PresentTerms"": ""Fetal Station"",
        ""SnomedId"": 289376009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Unit"": ""cm"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Fetus"",
        ""PresentTerms"": ""Fetal head moulding"",
        ""SnomedId"": 79114003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Fetus"",
        ""PresentTerms"": ""Fixed suture overlap"",
        ""SnomedId"": 249075004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Fetus"",
        ""PresentTerms"": ""Reducible suture overlap"",
        ""SnomedId"": 249074000,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Fetus"",
        ""PresentTerms"": ""Sutures touching without overlapping"",
        ""SnomedId"": 249073006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Fetus"",
        ""PresentTerms"": ""Number of Contractions"",
        ""SnomedId"": null,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""minutes"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Contractions"",
        ""PresentTerms"": ""Uterine contractions absent"",
        ""SnomedId"": 289701001,
        ""AbsentTerms"": ""Uterine contractions present"",
        ""AbsentTermsSnomedId"": 289700000,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Contractions"",
        ""PresentTerms"": ""Uterine contractions ceased"",
        ""SnomedId"": 289702008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Contractions"",
        ""PresentTerms"": ""Uterine contractions normal"",
        ""SnomedId"": 289738001,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Contractions"",
        ""PresentTerms"": ""Continuous contractions"",
        ""SnomedId"": 289724008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Contractions"",
        ""PresentTerms"": ""Regular uterine contractions"",
        ""SnomedId"": 289708007,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Intensity of contrations"",
        ""PresentTerms"": ""Fair uterine contractions"",
        ""SnomedId"": 289717007,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Intensity of contrations"",
        ""PresentTerms"": ""Good uterine contractions"",
        ""SnomedId"": 289718002,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Intensity of contrations"",
        ""PresentTerms"": ""Mild uterine contractions"",
        ""SnomedId"": 289715004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Intensity of contrations"",
        ""PresentTerms"": ""Moderate uterine contractions"",
        ""SnomedId"": 289716003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Intensity of contrations"",
        ""PresentTerms"": ""Strong uterine contractions"",
        ""SnomedId"": 289719005,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Cervical consistency"",
        ""SnomedId"": 289772009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Cervical Consistency"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Cervical position"",
        ""SnomedId"": 366311003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Cervical Position"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Cervical dilataion"",
        ""SnomedId"": 289825001,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Unit"": ""cm"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Cervical effacement"",
        ""SnomedId"": 366309007,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Cervical Effacement"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Cervical cerclage in-situ"",
        ""SnomedId"": 289827009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Cervical os closed"",
        ""SnomedId"": 281128000,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Cervical os open"",
        ""SnomedId"": 281127005,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Blood at cervical OS"",
        ""SnomedId"": 271690009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Membrane at cervical os"",
        ""SnomedId"": 249207000,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Mucus plug in os cervix"",
        ""SnomedId"": 248939006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Placental fragments at cervical os"",
        ""SnomedId"": 249206009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Products of conception at cervical OS"",
        ""SnomedId"": 248937008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Pus at cervical OS"",
        ""SnomedId"": 248938003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Cervix"",
        ""PresentTerms"": ""Cervix tender"",
        ""SnomedId"": 289815006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Amniotic sac"",
        ""PresentTerms"": ""Amniotic membranes intact"",
        ""SnomedId"": 249125003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Amniotic sac"",
        ""PresentTerms"": ""Drainage of liqour"",
        ""SnomedId"": 371380006,
        ""AbsentTerms"": ""No drainage of liqour observed"",
        ""AbsentTermsSnomedId"": 289572007,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Amniotic sac"",
        ""PresentTerms"": ""Amniotic fluid -meconium stain"",
        ""SnomedId"": 168092006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Amniotic sac"",
        ""PresentTerms"": ""Bloodstained liquor"",
        ""SnomedId"": 249134008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Amniotic sac"",
        ""PresentTerms"": ""Straw colored amniotic fluid"",
        ""SnomedId"": 408781009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Amniotic sac"",
        ""PresentTerms"": ""Cord prolapse"",
        ""SnomedId"": 270500004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Amniotic sac"",
        ""PresentTerms"": ""Cord round neck"",
        ""SnomedId"": null,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Perineum"",
        ""PresentTerms"": ""Central laceration during delivery"",
        ""SnomedId"": 90532005,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Perineum"",
        ""PresentTerms"": ""First degree perineal laceration"",
        ""SnomedId"": 57759005,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Perineum"",
        ""PresentTerms"": ""Fourth degree perineal laceration"",
        ""SnomedId"": 399031001,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Perineum"",
        ""PresentTerms"": ""Perineal laceration involving fourchette"",
        ""SnomedId"": 46311005,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Perineum"",
        ""PresentTerms"": ""Perineal laceration involving rectovaginal septum"",
        ""SnomedId"": 6825008,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Perineum"",
        ""PresentTerms"": ""Second degree perineal laceration"",
        ""SnomedId"": 6234006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Perineum"",
        ""PresentTerms"": ""Third degree perineal laceration"",
        ""SnomedId"": 10217006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Perineum"",
        ""PresentTerms"": ""Traumatic extension of episiotomy"",
        ""SnomedId"": 36497006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Vagina"",
        ""PresentTerms"": ""Vaginal show"",
        ""SnomedId"": 268471004,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Vagina"",
        ""PresentTerms"": ""No vaginal bleeding"",
        ""SnomedId"": 289542001,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Vagina"",
        ""PresentTerms"": ""Abnormal vaginal bleeding"",
        ""SnomedId"": 301822002,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Vaginal Bleed"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Vagina"",
        ""PresentTerms"": ""Fresh bleeding from vagina"",
        ""SnomedId"": 289536000,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Vaginal Bleed"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Vagina"",
        ""PresentTerms"": ""Passing altered blood from vagina"",
        ""SnomedId"": 289537009,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": ""Vaginal Bleed"",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Vagina"",
        ""PresentTerms"": ""Passing clots vaginally"",
        ""SnomedId"": 289532003,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    },
    {
        ""Header"": ""Vagina"",
        ""PresentTerms"": ""Hematoma of vagina during delivery"",
        ""SnomedId"": 46502006,
        ""AbsentTerms"": """",
        ""AbsentTermsSnomedId"": null,
        ""Site"": false,
        ""Plane"": false,
        ""Qualifiers"": """",
        ""Type"": ""Obstetrics""
    }
]";
    }
}