# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Production Deployment | Azure Web App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2

      - name: Setup Production environment variables
        uses: microsoft/variable-substitution@v1
        with:
          files: "**/*.Migrator/appsettings.json, **/*.Host/appsettings.Production.json"
        env:
          ConnectionStrings.Default: ${{ secrets.PRODUCTION_CONNECTION_STRING }}
          Sentry.Dsn: ${{ secrets.PRODUCTION_SENTRY_DSN }}
          Snowstorm.BaseUrl: ${{ secrets.SNOWSTORM_BASEURL }}
          FileStorage.AzureBlobStorage.ConnectionString: ${{ secrets.PRODUCTION_AZURE_STORAGE_CONNECTION_STRING }}

      - name: Setup general environment variables
        uses: microsoft/variable-substitution@v1
        with:
          files: "**/*.Host/appsettings.json"
        env:
          IpStack.ApiAccessKey: ${{ secrets.IPSTACK_API_ACCESS_KEY }}
          HostInformation.Name: ${{ vars.HOST_NAME }}
          HostInformation.Location: ${{ vars.HOST_ADDRESS }}
          HostInformation.Website: ${{ vars.HOST_WEBSITE }}
          HostInformation.TechnicalSupportEmail: ${{ vars.HOST_TECHNICAL_SUPPORT_EMAIL }}
          HostInformation.ContactSalesEmail: ${{ vars.HOST_CONTACT_SALES_EMAIL }}
          

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x"
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ./Plateaumed.EHR.Web.sln --configuration Release

      - name: dotnet publish
        working-directory: ./src/Plateaumed.EHR.Web.Host/
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: PostgreSQL Database Migration
        working-directory: ./src/Plateaumed.EHR.EntityFrameworkCore/
        run: |
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet tool install --global dotnet-ef --version 7.0
          dotnet tool restore
          dotnet ef database update --verbose --configuration Production --connection "$ConnectionString"
        env:
          ConnectionString: ${{ secrets.PRODUCTION_CONNECTION_STRING }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'plateaumed-ehr-api-live'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8CB86FB7AAB343B5A0CDDF7F6D1A7E90 }}
          package: .
