name: Deploy to Amazon ECS
on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT for OIDC
  contents: read

env:
  AWS_REGION: eu-west-2
  ECS_CLUSTER: Prod-Cluster
  ECS_TASK_DEFINITION: task-definition.json
  ECR_REPOSITORY: ${{ github.event.repository.name }}
  ECS_SERVICE: prod-${{ github.event.repository.name }}
  CONTAINER_NAME: prod-${{ github.event.repository.name }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image

        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          zip -r cypress-results-${{ env.DATE }}.zip build

